[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "password-audit"
version = "0.1.0"
description = "Active Directory password audit framework"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "rich>=13.0.0",
]

[project.scripts]
password-audit = "cli.main:main"

[tool.setuptools.packages.find]
include = [
    "cli",
    "common",
    "ntds",
    "analysis",
    "reports",
    "cracking",
    "auditing",
    "lm"
]

[project.optional-dependencies]
docs = [
    "mkdocs-material",
    "mkdocs-glightbox",
]