"""
Markdown report generation.

This module is responsible for rendering report content as
Markdown and writing the resulting output to disk.

Functions in this module should focus solely on Markdown
generation and export functionality.
"""

# ---------------------------------------------------------------------------
# Markdown Export
# ---------------------------------------------------------------------------

def render_markdown(report):
    """
    Render a password audit report as Markdown.

    Report sections are assembled into a standard structure
    containing the executive summary, technical commentary,
    and remediation guidance.

    Args:
        report (dict):
            Report content generated by the reporting modules.

    Returns:
        str:
            Complete Markdown report.
    """

    lines = []

    lines.append("# Executive Summary")
    lines.append("")
    lines.append(report["executive_summary"])
    lines.append("")

    lines.append("# Technical Commentary")
    lines.append("")
    lines.append(report["technical_commentary"])
    lines.append("")

    lines.append("# Remediation Guidance")
    lines.append("")
    lines.append(report["remediation_guidance"])
    lines.append("")

    return "\n".join(lines)


def write_markdown(path, content):
    """
    Write a Markdown report to disk.

    Args:
        path (str):
            Output file path.

        content (str):
            Markdown content to write.

    Returns:
        None
    """

    with open(path, "w", encoding="utf-8") as f:
        f.write(content)