"""
Remediation guidance generation.

This module converts analysis results into prioritised remediation
recommendations suitable for inclusion within password audit
reports.

Functions in this module should focus on producing remediation
guidance based on identified findings. Analysis logic should
remain within the analysis module.
"""

from common.utils import natural_join, num_to_word

def remediation_guidance(results):
    """
    Generate remediation guidance based on password audit findings.

    Recommendations are included conditionally based on the
    weaknesses identified during analysis. This ensures that the
    guidance remains relevant to the assessed environment and
    avoids presenting unnecessary recommendations where no
    supporting evidence exists.

    Recommendations may be generated for:

    - Privileged account security
    - Password policy compliance
    - Password reuse
    - Predictable password construction
    - Multi-factor authentication

    Args:
        results (dict):
            Analysis results generated by the password analysis
        engine.

    Returns:
        str:
            Remediation guidance formatted as Markdown-ready text.
    """

    lines = []

    # ------------------------
    # Introduction
    # ------------------------

    lines.append(
        "The following recommendations are based on the findings "
        "identified during the password audit. Remediation efforts "
        "should be prioritised according to business risk and aligned "
        "with the organisation's wider identity and access management "
        "strategy:\n"
    )

    # ------------------------
    # Privileged Accounts
    # ------------------------

    if results["admins"]["count"]:

        count = results["admins"]["count"]

        lines.append(
            "- The affected privileged accounts should have their passwords "
            "reset immediately and reviewed to ensure they are protected by "
            "strong, unique credentials. Consider applying enhanced controls "
            "to privileged identities, including dedicated password policies, "
            "privileged access management solutions, and multi-factor "
            "authentication.\n"
        )

    # -------------------------------
    # Password Length Compliance
    # -------------------------------

    if results["password_length"]["count"]:
        lines.append(
            "- Password policy settings should be reviewed to ensure that all accounts meet "
            "the organisation's baseline security requirements and that legacy or "
            "non-compliant credentials are remediated. Longer passwords and passphrases "
            "generally provide greater resistance to offline password-cracking attacks "
            "and should be encouraged wherever possible.\n"
        )

    # ---------------
    # Password Reuse
    # ---------------

    shared = results["password_reuse_general"]["sharedPasswords"]
    affected = results["password_reuse_general"]["sharedAccounts"]

    if shared:

        lines.append(
            "- Users should be encouraged to maintain unique passwords for all "
            "accounts and services. Where appropriate, password managers should "
            "be implemented to support the adoption of unique credentials and reduce "
            "reliance on reused passwords.\n"
        )

    # ------------------------
    # Similarly-named reuse
    # ------------------------

    if results["similar_account_reuse"]["count"]:

        lines.append(
            "- Administrative and standard user accounts should maintain "
            "separate credentials to preserve account separation and "
            "reduce the likelihood of privilege escalation following "
            "credential compromise.\n"
        )

    # -------------------------------
    # Password Construction Practices
    # -------------------------------

    patterns = []

    if results["username_passwords"]["count"]:
        patterns.append("username-derived content")

    if results["company_words"]["count"]:
        patterns.append("organisation-related terminology")

    if results["common_passwords"]["count"]:
        patterns.append("commonly used password terms")

    if results["date_passwords"]["count"]:
        patterns.append("date-related references")

    if results["keyboard_walks"]["count"]:
        patterns.append("keyboard sequences")

    if patterns:
        lines.append(
            f"- Recovered passwords were identified as containing "
            f"{natural_join(patterns)}. Users should select passwords "
            "that are unrelated to personal information, organisational "
            "terminology, or other predictable patterns. Technical "
            "controls such as password filtering solutions should also "
            "be considered to prevent the use of weak and commonly "
            "observed password constructions.\n"
        )

    # ----------------------------
    # Multi-Factor Authentication
    # ----------------------------

    lines.append(
        "Regardless of the specific weaknesses identified, multi-factor authentication (MFA) should be enforced for "
        "all externally accessible services and privileged accounts wherever technically feasible. Whilst strong "
        "passwords remain important, MFA provides additional protection against password-based attacks and reduces the "
        "likelihood of account compromise following credential exposure.\n"
    )

    return "\n".join(lines)