"""
Remediation guidance generation.

This module converts analysis results into prioritised remediation
recommendations suitable for inclusion within password audit
reports.

Functions in this module should focus on producing remediation
guidance based on identified findings. Analysis logic should
remain within the analysis module.
"""

def remediation_guidance(results):
    """
    Generate remediation guidance based on password audit findings.

    Recommendations are included conditionally based on the
    weaknesses identified during analysis. This ensures that the
    guidance remains relevant to the assessed environment and
    avoids presenting unnecessary recommendations where no
    supporting evidence exists.

    Recommendations may be generated for:

    - Privileged account security
    - Password policy compliance
    - Password reuse
    - Predictable password construction
    - Multi-factor authentication

    Args:
        results (dict):
            Analysis results generated by the password analysis
        engine.

    Returns:
        str:
            Remediation guidance formatted as Markdown-ready text.
    """

    lines = []

    # ------------------------
    # Introduction
    # ------------------------

    lines.append(
        "Remediation efforts should be prioritised according to business "
        "risk and aligned with the organisation's wider identity "
        "and access management strategy:\n"
    )

    # ------------------------
    # Privileged Accounts
    # ------------------------

    if results["admins"]["count"]:

        lines.append(
            "- The affected privileged accounts should have their passwords "
            "reset immediately and reviewed to ensure they are protected by "
            "strong, unique credentials. Consider applying enhanced controls "
            "to privileged identities, including dedicated password policies, "
            "privileged access management solutions, and multi-factor "
            "authentication."
        )

    # ------------------------
    # # Presence of LM hashes
    # ------------------------

    if results["lm_hashes"]["count"]:

        lines.append(
            "- LM hash storage should be disabled and affected users "
            "should be required to change their passwords to ensure "
            "that previously stored LM hashes are removed. Any legacy "
            "systems requiring LM compatibility should be identified "
            "and remediated where possible."
        )

    # ------------------------
    # Recovered LM passwords
    # ------------------------

    if results["lm_passwords"]["count"]:

        recommendation = (
            "- Accounts for which passwords were recovered from LM hashes "
            "should be required to change their passwords to invalidate "
            "previously recovered credentials."
        )

        # Domain Admins with LM hashes
        if results["lm_admins"]["count"]:

            recommendation += (
                " Privileged accounts should be prioritised for immediate "
                "password reset and reviewed for potential credential exposure."
            )

        lines.append(recommendation)

    # -------------------------------
    # Password Length Compliance
    # -------------------------------

    if results["password_length"]["count"]:
        lines.append(
            "- Password policy settings should be reviewed to ensure that all accounts meet "
            "the organisation's baseline security requirements and that legacy or "
            "non-compliant credentials are remediated. Longer passwords and passphrases "
            "generally provide greater resistance to offline password-cracking attacks "
            "and should be encouraged wherever possible."
        )

    # ---------------
    # Password Reuse
    # ---------------

    if results["password_reuse_general"]["sharedPasswords"]:

        lines.append(
            "- Users should be encouraged to maintain unique passwords for all "
            "accounts and services. Where appropriate, password managers should "
            "be implemented to support the adoption of unique credentials and reduce "
            "reliance on reused passwords."
        )

    # ------------------------
    # Similarly-named reuse
    # ------------------------

    if results["similar_account_reuse"]["count"]:

        lines.append(
            "- Administrative and standard user accounts should maintain "
            "separate credentials to preserve account separation and "
            "reduce the likelihood of privilege escalation following "
            "credential compromise."
        )

    # -------------------------------
    # Password Construction Practices
    # -------------------------------

    patterns = []

    if results["username_passwords"]["count"]:
        patterns.append("username-derived content")

    if results["company_words"]["count"]:
        patterns.append("organisation-related terminology")

    if results["common_passwords"]["count"]:
        patterns.append("commonly used password terms")

    if results["date_passwords"]["count"]:
        patterns.append("date-related references")

    if results["keyboard_walks"]["count"]:
        patterns.append("keyboard sequences")

    if patterns:
        lines.append(
            "- Users should select passwords that are unrelated "
            "to personal information, organisational terminology, "
            "or other predictable patterns. Technical controls such "
            "as password filtering solutions should also be considered "
            "to prevent the use of weak and commonly observed password "
            "constructions."
        )

    # ----------------------------
    # Multi-Factor Authentication
    # ----------------------------

    lines.append(
        "- Multi-factor authentication (MFA) should be enforced for "
        "all externally accessible services and privileged accounts "
        "wherever technically feasible. Whilst strong passwords remain "
        "important, MFA provides additional protection against password-"
        "based attacks and reduces the likelihood of account compromise "
        "following credential exposure."
    )

    return "\n".join(lines)


def remediation_references(results):
    """
        Generate remediation reference links based on
        identified findings.
    
        Returns:
            str: Markdown-formatted references section.
        """

    references = set()

    # Always include
    references.add("https://www.ncsc.gov.uk/collection/passwords")
    references.add("https://www.ncsc.gov.uk/guidance/multi-factor-authentication-online-services")
    references.add("https://pages.nist.gov/800-63-4/sp800-63b.html#appA")

    # Privileged accounts
    if results["admins"]["count"]:
        references.add(
            "https://learn.microsoft.com/security/privileged-access-workstations/privileged-access-access-model"
        )
        references.add(
            "https://learn.microsoft.com/en-us/microsoft-365/admin/misc/password-policy-recommendations?view=o365-worldwide#password-guidelines-for-administrators"
        )
        references.add(
            "https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc770394(v=ws.10)"
        )

    # Presence of LM hashes
    if results["lm_hashes"]["count"]:
        references.add(
            "https://learn.microsoft.com/windows/security/threat-protection/security-policy-settings/network-security-do-not-store-lan-manager-hash-value-on-next-password-change"
        )

    # Password reuse
    if (
        results["password_reuse_general"]["sharedPasswords"]
        or results["similar_account_reuse"]["count"]
    ):
        references.add(
            "https://specopssoft.com/blog/password-reuse-hidden-danger/"
        )

    # Predictable patterns
    if (
        results["username_passwords"]["count"]
        or results["company_words"]["count"]
        or results["common_passwords"]["count"]
        or results["date_passwords"]["count"]
        or results["keyboard_walks"]["count"]
    ):
        references.add(
            "https://www.ncsc.gov.uk/blog-post/the-logic-behind-three-random-words"
        )

    return "\n".join(f"- [{url}]({url})" for url in sorted(references))